services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gdop_network
    depends_on:
      - db
      - django-web
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - gdop_network
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - gdop_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
  django-web:
    build: .
    container_name: django-docker
    # ports:
    #   - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - gdop_network
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}

      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}

      ALLOWED_HOSTS: "*"
    env_file:
      - .env
volumes:
  postgres_data:
  uploads:
networks:
  gdop_network:
    driver: bridge
