# Generated by Django 5.1.4 on 2024-12-31 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='subtitle',
        ),
    ]
