# Generated by Django 5.1.4 on 2024-12-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0002_alter_herosection_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(default='bi-people', help_text='Bootstrap icon class name (e.g., bi-people', max_length=100),
            preserve_default=False,
        ),
    ]
