# Generated by Django 5.1.4 on 2024-12-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0003_project_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='icon_name',
            field=models.CharField(default='bi-people', help_text='Bootstrap icon class name (e.g., bi-people', max_length=100),
            preserve_default=False,
        ),
    ]
