# Generated by Django 5.1.4 on 2024-12-31 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0004_announcement_icon_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='bullet_points',
            field=models.CharField(default='', help_text='Comma separated list of bullet points', max_length=255),
            preserve_default=False,
        ),
    ]
