# Generated by Django 5.1.4 on 2024-12-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0005_alter_aboutus_options_aboutus_bullet_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
