# Generated by Django 5.1.4 on 2024-12-31 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0006_aboutus_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberstatistic',
            options={'verbose_name': 'Numbers', 'verbose_name_plural': 'Numbers'},
        ),
        migrations.AddField(
            model_name='numberstatistic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 31, 4, 1, 8, 106766)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numberstatistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
