# Generated by Django 5.1.4 on 2025-01-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0011_alter_gdopcomponent_options_alter_resource_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='slug',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the announcement', null=True, upload_to='uploads/announcements/'),
        ),
    ]
