# Generated by Django 5.1.4 on 2025-01-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0013_supportrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportrequest',
            old_name='full_name',
            new_name='name',
        ),
    ]
