# Generated by Django 5.1.4 on 2025-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0014_rename_full_name_supportrequest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
