# Generated by Django 5.1.4 on 2025-01-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0019_alter_teammember_email_alter_teammember_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
