# Generated by Django 5.1.4 on 2025-01-09 01:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0024_remove_gdopcomponent_button_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FocusArea',
            new_name='AboutUsFooter',
        ),
        migrations.AlterModelOptions(
            name='aboutusfooter',
            options={'verbose_name': 'About Us (Footer)', 'verbose_name_plural': 'About Us (Footer)'},
        ),
    ]
