# Generated by Django 5.1.4 on 2025-01-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0025_rename_focusarea_aboutusfooter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdopcomponent',
            name='redirect_url',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
