# Generated by Django 5.1.4 on 2025-01-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0026_gdopcomponent_redirect_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gdopcomponent',
            options={'verbose_name': 'GDOP Module', 'verbose_name_plural': 'GDOP Modules'},
        ),
    ]
