# Generated by Django 5.1.4 on 2025-01-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0027_alter_gdopcomponent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='FTP Server Host', max_length=255)),
                ('port', models.IntegerField(help_text='FTP Server Port')),
                ('user', models.CharField(help_text='FTP User', max_length=255)),
                ('password', models.CharField(help_text='FTP Password', max_length=255)),
                ('network_folder_path', models.CharField(help_text='Network Folder Path', max_length=255)),
                ('metadata_file', models.CharField(default='metadata.json', help_text='Metadata File Name', max_length=255)),
            ],
        ),
    ]
