# Generated by Django 5.1.4 on 2025-01-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0028_ftpconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ftpconfiguration',
            options={'verbose_name': 'FTP Configuration', 'verbose_name_plural': 'FTP Configurations'},
        ),
        migrations.AlterField(
            model_name='ftpconfiguration',
            name='password',
            field=models.CharField(blank=True, help_text='FTP Password', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ftpconfiguration',
            name='user',
            field=models.CharField(blank=True, help_text='FTP User', max_length=255, null=True),
        ),
    ]
