# Generated by Django 5.1.4 on 2025-01-18 03:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0029_alter_ftpconfiguration_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GDOPComponent',
            new_name='GDOPModule',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='Figure',
        ),
        migrations.DeleteModel(
            name='HeroSection',
        ),
    ]
