# Generated by Django 5.1.4 on 2025-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0030_rename_gdopcomponent_gdopmodule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdopmodule',
            name='image',
            field=models.ImageField(default='', help_text='Image for the component', upload_to='uploads/components/'),
            preserve_default=False,
        ),
    ]
