# Generated by Django 5.1.4 on 2025-01-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0031_alter_gdopmodule_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
