# Generated by Django 5.1.4 on 2025-01-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mint_landing', '0033_resourcecategory_pdfresource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
